name: Makefile CI

on:
  push:
  check_run:
  schedule:
    - cron: "30 23 * * *"
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'crpb/fnt'
        ref: 'mirror'
    - name: generate index
      run: |
         ./update.sh
         git config --global user.email "runner@moo.tld"
         git config --global user.name "Moo Run"
         #git add OFL.xz APACHE.xz
         if git commit --all -m $(date -Im); then
           git push
         fi
